---
default_stages: [commit, push]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: check-json
      - id: pretty-format-json
      - id: check-yaml
      - id: check-merge-conflict
      - id: detect-private-key
      - id: no-commit-to-branch

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v1.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies:
          - "@commitlint/config-conventional"
          - conventional-changelog-conventionalcommits

  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.9.1
    hooks:
      - id: check-github-workflows
      - id: check-github-actions

-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.7.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: eslint

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.5.1'  # Use the sha / tag you want to point at
    hooks:
    -   id: prettier
